import requests

# 构造发送的 XML 数据
xml_data_new = """
<Request>
    <Header>
        <SourceSystem>02</SourceSystem>
        <MessageID>593990</MessageID>
    </Header>
    <Body>
        <PATPatientInfo>
            <HospitalCode>F0001</HospitalCode>
            <PATPatientID>0037216733</PATPatientID>
            <PATName>测试李叁</PATName>
            <PATDob>2010-08-06</PATDob>
            <PATAge>14岁</PATAge>
            <PATSexCode>F</PATSexCode>
            <PATSexDesc>女</PATSexDesc>
            <PATMaritalStatusCode>1</PATMaritalStatusCode>
            <PATMaritalStatusDesc>已婚</PATMaritalStatusDesc>
            <PATDocumentNo></PATDocumentNo>
            <PATNationCode>01</PATNationCode>
            <PATNationDesc>HZ-汉族</PATNationDesc>
            <PATAddress>1</PATAddress>
            <PATCountryCode>CHN</PATCountryCode>
            <PATCountryDesc>ZG-中国</PATCountryDesc>
            <PATDeceasedDate></PATDeceasedDate>
            <PATDeceasedTime></PATDeceasedTime>
            <PATHealthCardID></PATHealthCardID>
            <PATMotherID></PATMotherID>
            <PATOccupationCode>11</PATOccupationCode>
            <PATOccupationDesc>国家公务员</PATOccupationDesc>
            <PATWorkPlaceName></PATWorkPlaceName>
            <PATWorkPlaceTelNum></PATWorkPlaceTelNum>
            <PATIdentityNum>469023193202295911</PATIdentityNum>
            <PATIdTypeCode>01</PATIdTypeCode>
            <PATIdTypeDesc>身份证-1</PATIdTypeDesc>
            <PATRelationName>测试</PATRelationName>
            <PATRelationPhone>17318650509</PATRelationPhone>
            <PATTelephone>18980605768</PATTelephone>
            <PATRemarks></PATRemarks>
        </PATPatientInfo>
        <PATAdmInfo>
            <PAADMVisitNumber>178687042</PAADMVisitNumber>
            <PAADMVisitTimes></PAADMVisitTimes>
            <PAADMTypeCode>I</PAADMTypeCode>
            <PAADMTypeDesc>住院</PAADMTypeDesc>
            <PAAdmStatusCode>A</PAAdmStatusCode>
            <PAAdmStatusDesc>就诊</PAAdmStatusDesc>
            <PAADMDocCode>20198192</PAADMDocCode>
            <PAADMDocDesc>姚琼</PAADMDocDesc>
            <PAADMStartDate>2023-11-20</PAADMStartDate>
            <PAADMStartTime>14:25:35</PAADMStartTime>
            <PAADMDeptCode>7849</PAADMDeptCode>
            <PAADMDeptDesc>测试第一医疗单元</PAADMDeptDesc>
            <PAADMAdmWardCode>7852</PAADMAdmWardCode>
            <PAADMAdmWardDesc>测试第二护理单元</PAADMAdmWardDesc>
            <PAADMCurBedNo></PAADMCurBedNo>
            <PAADMCurDeptCode>7849</PAADMCurDeptCode>
            <PAADMCurDeptDesc>测试第一医疗单元</PAADMCurDeptDesc>
            <PAADMFeeTypeCode>0000</PAADMFeeTypeCode>
            <PAADMFeeTypeDesc>市医保</PAADMFeeTypeDesc>
            <PAADMHosCode>F0001</PAADMHosCode>
            <PAADMNO>IP0005051621</PAADMNO>
            <AdmissonType></AdmissonType>
            <Pattag>3</Pattag>
            <PatType></PatType>
            <Chaint></Chaint>
            <Mehistory></Mehistory>
            <Hemogram></Hemogram>
            <Mesituation></Mesituation>
            <Inspresults></Inspresults>
            <Chestpain></Chestpain>
            <Phycycle></Phycycle>
            <Height></Height>
            <weight></weight>
            <PEEpisodeNo></PEEpisodeNo>
        </PATAdmInfo>
        <AddRisAppBillRt>
            <OrderList>
                <RISRAppNum></RISRAppNum>
                <RISRExamID>175923714-3125</RISRExamID>
                <RISRMattersAttention></RISRMattersAttention>
                <RISRSpecalMedicalRecord></RISRSpecalMedicalRecord>
                <AppDeptCode>7849</AppDeptCode>
                <AppDeptDesc>测试第一医疗单元</AppDeptDesc>
                <RISRSubmitDocCode>YW03714</RISRSubmitDocCode>
                <RISRSubmitDocDesc>郭子瑜</RISRSubmitDocDesc>
                <RISRSubmitTime>2025-05-14 14:24:24</RISRSubmitTime>
                <RISRAcceptDeptCode>7820</RISRAcceptDeptCode>
                <RISRAcceptDeptDesc>心理卫生中心医疗单元</RISRAcceptDeptDesc>
                <RISRDeptLocation></RISRDeptLocation>
                <RISRISEmergency></RISRISEmergency>
                <RISRClinicalSymptoms>1,高血压2,肺结节病3,头痛4,实验室检查5,食入毒蘑菇中毒6,食物中毒7,瘦弱营养不良8,营养不良9,营养不良10,体寒11,低血压12,流行性感冒</RISRClinicalSymptoms>
                <OEORIOrderItemID>175923714||3125</OEORIOrderItemID>
                <RISRPositionCode></RISRPositionCode>
                <RISRPostureCode></RISRPostureCode>
                <RISRCode>666902216</RISRCode>
                <RISRRemark></RISRRemark>
                <RISRDesc>植物神经稳定性检查</RISRDesc>
                <RISRPrice>54.00</RISRPrice>
                <OrdSubCatCode>0223</OrdSubCatCode>
                <OrdSubCatDesc>心理评估与治疗</OrdSubCatDesc>
                <OrdCatCode>02</OrdCatCode>
                <OrdCatDesc>治疗</OrdCatDesc>
                <UpdateUserCode></UpdateUserCode>
                <UpdateUserDesc></UpdateUserDesc>
                <UpdateDate></UpdateDate>
                <UpdateTime></UpdateTime>
                <ContrastMaterial></ContrastMaterial>
                <ContrastNum></ContrastNum>
                <IsAbFlag>Y</IsAbFlag>
                <OperationSign></OperationSign>
                <AppNo></AppNo>
                <Exampart></Exampart>
                <KYTYPE>KYJJ</KYTYPE>
                <KyProjectNo></KyProjectNo>
                <KyProjectName></KyProjectName>
                <Notes></Notes>
                <AdmISEmerg></AdmISEmerg>
            </OrderList>
        </AddRisAppBillRt>
    </Body>
</Request>"""








xml_data = """<Request>
    <Header>
        <SourceSystem>HIS</SourceSystem>
        <MessageID>5</MessageID>
    </Header>
    <Body>
        <PATPatientInfo>
            <HospitalCode>F0001</HospitalCode>
            <PATPatientID>0037216733</PATPatientID>
            <PATName>测试李叁</PATName>
            <PATDob>1932-02-29</PATDob>
            <PATAge>92</PATAge>
            <PATSexCode>F</PATSexCode>
            <PATSexDesc></PATSexDesc>
            <PATMaritalStatusCode>1</PATMaritalStatusCode>
            <PATMaritalStatusDesc>已婚</PATMaritalStatusDesc>
            <PATDocumentNo></PATDocumentNo>
            <PATNationCode>01</PATNationCode>
            <PATNationDesc>HZ-汉族</PATNationDesc>
            <PATAddress></PATAddress>
            <PATCountryCode>CHN</PATCountryCode>
            <PATCountryDesc>ZG-中国</PATCountryDesc>
            <PATDeceasedDate></PATDeceasedDate>
            <PATDeceasedTime></PATDeceasedTime>
            <PATHealthCardID></PATHealthCardID>
            <PATMotherID></PATMotherID>
            <PATOccupationCode>11</PATOccupationCode>
            <PATOccupationDesc>国家公务员</PATOccupationDesc>
            <PATWorkPlaceName></PATWorkPlaceName>
            <PATWorkPlaceTelNum></PATWorkPlaceTelNum>
            <PATIdentityNum>110101201507282202</PATIdentityNum>
            <PATIdTypeCode>14</PATIdTypeCode>
            <PATIdTypeDesc>全国组织机构代码</PATIdTypeDesc>
            <PATRelationName>测试</PATRelationName>
            <PATRelationPhone>17318650509</PATRelationPhone>
            <PATTelephone>18980605768</PATTelephone>
            <PATRemarks></PATRemarks>
        </PATPatientInfo>
        <PATAdmInfo>
            <PAADMVisitNumber>178687042</PAADMVisitNumber>
            <PAADMVisitTimes></PAADMVisitTimes>
            <PAADMTypeCode>I</PAADMTypeCode>
            <PAADMTypeDesc>住院</PAADMTypeDesc>
            <PAAdmStatusCode>A</PAAdmStatusCode>
            <PAAdmStatusDesc>就诊</PAAdmStatusDesc>
            <PAADMDocCode>20198192</PAADMDocCode>
            <PAADMDocDesc>姚琼</PAADMDocDesc>
            <PAADMStartDate>2023-11-20</PAADMStartDate>
            <PAADMStartTime>14:25:35</PAADMStartTime>
            <PAADMDeptCode>7849</PAADMDeptCode>
            <PAADMDeptDesc>测试第一医疗单元</PAADMDeptDesc>
            <PAADMAdmWardCode>7852</PAADMAdmWardCode>
            <PAADMAdmWardDesc>测试第二护理单元</PAADMAdmWardDesc>
            <PAADMCurBedNo>001床</PAADMCurBedNo>
            <PAADMCurDeptCode>7849</PAADMCurDeptCode>
            <PAADMCurDeptDesc>测试第一医疗单元</PAADMCurDeptDesc>
            <PAADMFeeTypeCode>01</PAADMFeeTypeCode>
            <PAADMFeeTypeDesc>现金</PAADMFeeTypeDesc>
            <PAADMHosCode>F0001</PAADMHosCode>
            <AdmissonType></AdmissonType>
            <Pattag></Pattag>
            <PatType></PatType>
            <Chaint></Chaint>
            <Mehistory></Mehistory>
            <Hemogram></Hemogram>
            <Mesituation></Mesituation>
            <Inspresults></Inspresults>
            <Chestpain></Chestpain>
            <Phycycle></Phycycle>
            <Height>168</Height>
            <Weight></Weight>
        </PATAdmInfo>
        <AddRisAppBillRt>
            <OrderList>
                <RISRAppNum></RISRAppNum>
                <RISRExamID>175923714-976</RISRExamID>
                <RISRMattersAttention></RISRMattersAttention>
                <RISRSpecalMedicalRecord></RISRSpecalMedicalRecord>
                <AppDeptCode>7849</AppDeptCode>
                <AppDeptDesc>测试第一医疗单元</AppDeptDesc>
                <RISRSubmitDocCode>YW03714</RISRSubmitDocCode>
                <RISRSubmitDocDesc>郭子瑜</RISRSubmitDocDesc>
                <RISRSubmitTime>2024-07-12 15:48:42</RISRSubmitTime>
                <RISRAcceptDeptCode>4185</RISRAcceptDeptCode>
                <RISRAcceptDeptDesc>临床营养科</RISRAcceptDeptDesc>
                <RISRDeptLocation></RISRDeptLocation>
                <RISRISEmergency></RISRISEmergency>
                <RISRClinicalSymptoms>1,高血压2,肺结节病</RISRClinicalSymptoms>
                <OEORIOrderItemID>175923714||976</OEORIOrderItemID>
                <RISRPositionCode></RISRPositionCode>
                <RISRPostureCode></RISRPostureCode>
                <RISRCode>666902395</RISRCode>
                <RISRDesc>能量代谢测定</RISRDesc>
                <RISRPrice>260.00</RISRPrice>
                <OrdSubCatCode>80</OrdSubCatCode>
                <OrdSubCatDesc>专科检查</OrdSubCatDesc>
                <OrdCatCode>03</OrdCatCode>
                <OrdCatDesc>检查</OrdCatDesc>
                <UpdateUserCode></UpdateUserCode>
                <UpdateUserDesc></UpdateUserDesc>
                <UpdateDate></UpdateDate>
                <UpdateTime></UpdateTime>
                <RISRRemark></RISRRemark>
                <AppNo></AppNo>
                <Exampart></Exampart>
                <KYTYPE>KYJJ</KYTYPE>
                <KyProjectNo></KyProjectNo>
                <KyProjectName></KyProjectName>
                <AdmISEmerg></AdmISEmerg>
                <Notes></Notes>
            </OrderList>
        </AddRisAppBillRt>
    </Body>
</Request>"""

# 发送 POST 请求
response = requests.post("http://127.0.0.1:5000/his/patient_info", data=xml_data_new, headers={"Content-Type": "application/xml"})

# 打印返回的响应内容
print(response.text)